### ISSUE TITLE
Feature: Proper Testing

### ISSUE THREAD

**Issue by MykalMachon** [MykalMachon/FormStore#6]
## Summary of PR
I need proper testing for this library.
We should be able to run DOM tests to see if the form is properly being stored. I don't think jest / vitest supports indexeddb, but we can build in a fallback that relies on localstorage maybe? 

## Todos
- [ ] Write some basic tests with vitest and make them required before publish
- [ ] Write a fallback to local storage if indexeddb is not available (this is a good idea anyways) 
- [ ] Write a form test that actually validates the app is doing what it's supposed to do.
